### ISSUE TITLE
plot_ns_sun_lc.pro not plotting RHESSI light curves

### ISSUE THREAD

**Issue by PaulJWright** [ianan/nsigh_all#1]
`plot_ns_sun_lc.pro` doesn't plot RHESSI light curves for some observations that have RHESSI data. The issue seems to be with the line:

`if (obsname eq '201604' or obsname eq '201805' or obsname ne '201809_07' or obsname ne '201809_10' or obsname ne '201809_11') then begin`

**Comment by ianan** [comment]
Should be fixed now.

Using plot_ns_sun_lc_rmn.pro for 2018 data, so just removed all 2018 data/refs from plot_ns_sun_lc.pro, which should fix the if statement. Should only be one case of not plotting RHESSI pre-2018 in that code.
